version: 2

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    settings:
      shadow:
        strict: false

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 140

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentFormatting
      - commentedOutCode

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell
    - unconvert
    - dupl
    - goconst
    - gocognit
    - lll
    - gocritic
    - bodyclose
    - noctx
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
